# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20160215_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=600)),
                ('subject', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='beacon',
            name='store',
        ),
        migrations.RemoveField(
            model_name='beacon',
            name='user',
        ),
        migrations.RemoveField(
            model_name='campaing',
            name='store',
        ),
        migrations.RemoveField(
            model_name='store',
            name='user',
        ),
        migrations.DeleteModel(
            name='Beacon',
        ),
        migrations.DeleteModel(
            name='Campaing',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
